# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_calc_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_New_calc(object):
    def setupUi(self, New_calc):
        New_calc.setObjectName("New_calc")
        New_calc.resize(506, 376)
        self.centralwidget = QtWidgets.QWidget(New_calc)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AppleSDGothicNeoT00")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(120, 70, 371, 31))
        font = QtGui.QFont()
        font.setFamily("AppleSDGothicNeoT00")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.button1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_1.setGeometry(QtCore.QRect(60, 170, 89, 25))
        self.button1_1.setObjectName("button1_1")
        self.button1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_2.setGeometry(QtCore.QRect(170, 170, 89, 25))
        self.button1_2.setObjectName("button1_2")
        self.button1_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_9.setGeometry(QtCore.QRect(280, 270, 89, 25))
        self.button1_9.setObjectName("button1_9")
        self.button1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_3.setGeometry(QtCore.QRect(280, 170, 89, 25))
        self.button1_3.setObjectName("button1_3")
        self.button1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_4.setGeometry(QtCore.QRect(60, 220, 89, 25))
        self.button1_4.setObjectName("button1_4")
        self.button1_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_5.setGeometry(QtCore.QRect(170, 220, 89, 25))
        self.button1_5.setObjectName("button1_5")
        self.button1_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_6.setGeometry(QtCore.QRect(280, 220, 89, 25))
        self.button1_6.setObjectName("button1_6")
        self.button1_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_7.setGeometry(QtCore.QRect(60, 270, 89, 25))
        self.button1_7.setObjectName("button1_7")
        self.button1_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_8.setGeometry(QtCore.QRect(170, 270, 89, 25))
        self.button1_8.setObjectName("button1_8")
        self.button1_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_0.setGeometry(QtCore.QRect(170, 320, 89, 25))
        self.button1_0.setObjectName("button1_0")
        self.resultButton = QtWidgets.QPushButton(self.centralwidget)
        self.resultButton.setGeometry(QtCore.QRect(280, 320, 89, 25))
        self.resultButton.setObjectName("resultButton")
        self.buttonPlus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPlus.setGeometry(QtCore.QRect(390, 170, 89, 25))
        self.buttonPlus.setObjectName("buttonPlus")
        self.buttonMinus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMinus.setGeometry(QtCore.QRect(390, 220, 89, 25))
        self.buttonMinus.setObjectName("buttonMinus")
        self.buttonMulti = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMulti.setGeometry(QtCore.QRect(390, 270, 89, 25))
        self.buttonMulti.setObjectName("buttonMulti")
        self.buttonDivide = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDivide.setGeometry(QtCore.QRect(390, 320, 89, 25))
        self.buttonDivide.setObjectName("buttonDivide")
        New_calc.setCentralWidget(self.centralwidget)

        self.retranslateUi(New_calc)
        QtCore.QMetaObject.connectSlotsByName(New_calc)

    def retranslateUi(self, New_calc):
        _translate = QtCore.QCoreApplication.translate
        New_calc.setWindowTitle(_translate("New_calc", "MainWindow"))
        self.label.setText(_translate("New_calc", "result :"))
        self.button1_1.setText(_translate("New_calc", "1"))
        self.button1_2.setText(_translate("New_calc", "2"))
        self.button1_9.setText(_translate("New_calc", "9"))
        self.button1_3.setText(_translate("New_calc", "3"))
        self.button1_4.setText(_translate("New_calc", "4"))
        self.button1_5.setText(_translate("New_calc", "5"))
        self.button1_6.setText(_translate("New_calc", "6"))
        self.button1_7.setText(_translate("New_calc", "7"))
        self.button1_8.setText(_translate("New_calc", "8"))
        self.button1_0.setText(_translate("New_calc", "0"))
        self.resultButton.setText(_translate("New_calc", "="))
        self.buttonPlus.setText(_translate("New_calc", "+"))
        self.buttonMinus.setText(_translate("New_calc", "-"))
        self.buttonMulti.setText(_translate("New_calc", "-"))
        self.buttonDivide.setText(_translate("New_calc", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    New_calc = QtWidgets.QMainWindow()
    ui = Ui_New_calc()
    ui.setupUi(New_calc)
    New_calc.show()
    sys.exit(app.exec_())
